# Generated by Django 5.2.5 on 2025-08-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoryGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_prompt", models.TextField()),
                ("story", models.TextField(blank=True)),
                ("character_description", models.TextField(blank=True)),
                ("background_description", models.TextField(blank=True)),
                ("character_image_prompt", models.TextField(blank=True)),
                ("background_image_prompt", models.TextField(blank=True)),
                (
                    "combined_image",
                    models.ImageField(blank=True, upload_to="generated_images/"),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="audio_uploads/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
